import { useEffect, useState } from 'react';
import { ArrowDownToLine, Search, SlidersHorizontal, Table2 } from 'lucide-react';
import AdminSidebar from '../../../components/AdminSidebar';
import ProductFilters, { emptyFilters } from '../../../components/ProductFilters';
import CheckGroup from '../../../components/CheckGroup';
import { request, downloadExcel, queryString } from '../../../utils/api';
const initial={...emptyFilters,status:'all',search:''};
const money=v=>Number(v||0).toLocaleString('es-MX',{style:'currency',currency:'MXN'});
export default function ProductReportsAdmin(){
 const [options,setOptions]=useState({brands:[],categories:[],colors:[],powers:[],columns:[]});
 const [filters,setFilters]=useState(initial),[columns,setColumns]=useState([]),[data,setData]=useState({rows:[],total:0,units:0,retailValue:0});
 const [page,setPage]=useState(1),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{request('/api/reports/products/options').then(o=>{setOptions(o);setColumns(o.columns.map(c=>c.key));}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{let live=true;setLoading(true);const t=setTimeout(()=>request('/api/reports/products?'+queryString({...filters,page})).then(d=>{if(live){setData(d);setError('');}}).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false)),250);return()=>{live=false;clearTimeout(t);};},[filters,page]);
 function update(next){setFilters(next);setPage(1);}
 async function exportReport(){setBusy(true);setError('');try{await downloadExcel('/api/reports/products/export?'+queryString({...filters,columns}),'ColorLenses-Productos.xlsx');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="admin-page cl-admin"><AdminSidebar/><main className="admin-content cl-admin-content"><header className="cl-page-heading"><div><span className="cl-eyebrow">ADMINISTRACIÓN / REPORTES</span><h1>Tu inventario, a tu medida.</h1><p>Combina marcas, graduaciones, categorías y colores. Exporta únicamente las columnas que necesitas.</p></div><button className="cl-btn" disabled={busy||!columns.length} onClick={exportReport}><ArrowDownToLine size={18}/>{busy?'Generando Excel…':'Exportar Excel'}</button></header>
 {error&&<div className="cl-alert cl-alert-danger" role="alert">{error}</div>}
 <div className="cl-report-layout"><aside className="cl-panel cl-report-filters"><div className="cl-panel-heading"><h2><SlidersHorizontal size={18}/> Filtros</h2><button className="cl-text-btn" onClick={()=>update(initial)}>Limpiar</button></div><label className="cl-search"><Search size={17}/><input placeholder="Modelo, código o palabra" value={filters.search} onChange={e=>update({...filters,search:e.target.value})}/></label><ProductFilters filters={filters} onChange={update} options={options}/><label className="cl-field">Estado<select value={filters.status} onChange={e=>update({...filters,status:e.target.value})}><option value="all">Todos</option><option value="active">Activos</option><option value="inactive">Inactivos</option><option value="pending">Pendientes de completar</option></select></label><CheckGroup title="Columnas del Excel" options={options.columns.map(c=>({value:c.key,label:c.title}))} value={columns} onChange={setColumns}/><p className="cl-table-note">Seleccionadas: {columns.length}. El Excel exporta todas las coincidencias, no solo esta página.</p></aside>
 <div className="cl-report-results"><div className="cl-metric-grid"><article><span>Variantes encontradas</span><strong>{Number(data.total).toLocaleString('es-MX')}</strong><small>Una fila por variante</small></article><article><span>Unidades en stock</span><strong>{Number(data.units).toLocaleString('es-MX')}</strong><small>Según los filtros elegidos</small></article><article><span>Valor a precio de venta</span><strong className="cl-metric-money">{money(data.retailValue)}</strong><small>No representa costo ni utilidad</small></article></div>
 <section className="cl-panel"><div className="cl-panel-heading"><div><span className="cl-eyebrow">VISTA PREVIA</span><h2>Productos y existencias</h2></div><Table2 size={23}/></div><div className="cl-table-wrap"><table className="cl-data-table"><thead><tr><th>Modelo / código</th><th>Marca</th><th>Categoría / color</th><th>Graduación</th><th>Stock</th><th>Precio</th><th>Estado</th></tr></thead><tbody>{data.rows.map(p=><tr key={p.ProductVariantId}><td className="cl-product-identity"><strong>{p.Modelo||"Modelo por completar"}</strong><small><code>{p.ScanCode||p.FactoryCode||p.InternalCode||"Sin código"}</code></small></td><td>{p.Marca}</td><td>{p.Category||'Por completar'}<small>{p.Color||'Por completar'}</small></td><td>{Number(p.NeedsReview)?'Por confirmar':p.PowerLabel||String(p.Power)}</td><td><strong>{p.Stock}</strong></td><td>{money(p.Price)}</td><td>{Number(p.NeedsReview)?'Pendiente':p.VariantStatus}</td></tr>)}</tbody></table></div>{loading?<p className="cl-empty">Consultando productos…</p>:!data.total&&<p className="cl-empty">No hay productos con esta combinación de filtros.</p>}<div className="cl-pagination"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page} de {Math.max(1,Math.ceil(data.total/25))}</span><button disabled={page*25>=data.total} onClick={()=>setPage(page+1)}>Siguiente</button></div></section><p className="cl-table-note">Los códigos se guardan como texto para conservar los ceros iniciales. Los importes y cantidades son numéricos; el reporte incluye totales y la configuración utilizada.</p></div></div>
 </main></div>;
}
