import BrandLogo from './BrandLogo';
import { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { LayoutDashboard, ScanLine, ShoppingBag, Users, Package, Boxes, FileSpreadsheet, History, Settings, LogOut, Menu, X, ArrowUpRight, CircleUserRound } from 'lucide-react';
export default function AdminSidebar(){
 const location=useLocation(),navigate=useNavigate(),[open,setOpen]=useState(false);
 let user={};try{user=JSON.parse(localStorage.getItem('adminUser')||'{}')||{};}catch{/* Invalid display data must not break the app. */}
 const name=user.fullName||user.FullName||user.username||user.Username||'Administrador';
 const groups=[{title:'OPERACIÓN',items:[['Resumen','/admin',LayoutDashboard],['Inventario','/admin/inventory',Boxes],['Productos','/admin/products',Package],['Vender','/admin/sales',ShoppingBag],['Vender con QR','/admin/scan',ScanLine]]},{title:'TU NEGOCIO',items:[['Reportes Excel','/admin/reports/products',FileSpreadsheet],['Historial de ventas','/admin/sales-history',History],['Clientes','/admin/customers',Users],['Configuración','/admin/settings',Settings]]}];
 function logout(){if(!window.confirm('¿Cerrar sesión? Los inventarios guardados se conservarán.'))return;localStorage.removeItem('adminToken');localStorage.removeItem('adminUser');navigate('/admin/login');}
 return <><header className="cl-admin-topbar"><button className="cl-icon-btn cl-admin-mobile-toggle" aria-label={open?'Cerrar menú':'Abrir menú administrativo'} aria-expanded={open} aria-controls="cl-admin-navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><span className="cl-admin-brandline"><Link to="/admin" aria-label="ColorLenses, centro de control"><BrandLogo compact/></Link><small>CENTRO DE CONTROL</small></span><div><CircleUserRound size={18}/><span>{name}</span></div></header>{open&&<div className="sidebar-overlay" onClick={()=>setOpen(false)}/>}
 <aside id="cl-admin-navigation" className={'admin-sidebar cl-admin-sidebar '+(open?'open':'')}><Link className="cl-admin-brand" to="/admin"><BrandLogo dark/></Link><nav className="sidebar-menu">{groups.map(g=><div className="cl-nav-group" key={g.title}><span className="cl-sidebar-label">{g.title}</span>{g.items.map(([label,path,Icon])=>{const active=path==='/admin'?location.pathname===path:location.pathname===path||location.pathname.startsWith(path+'/');return <Link key={path} to={path} aria-current={active?'page':undefined} className={active?'active':''} onClick={()=>setOpen(false)}><Icon size={18}/><span>{label}</span></Link>})}</div>)}</nav><div className="cl-sidebar-bottom"><Link to="/"><ArrowUpRight size={17}/> Ver tienda</Link><button onClick={logout}><LogOut size={17}/> Cerrar sesión</button><small>COLORLENSES / 3.0.1</small></div></aside></>;
}
