// Pruebas unitarias: no conectan con ninguna base de datos.
'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {codeValue,text,positiveInteger,requestKey,sameBrand,transaction,assertBrandUnlocked}=require('../lib/inventory-core');
const {matchesProduct,categoryKey,filtersFromQuery}=require('../lib/product-filters');
const {consolidated}=require('../lib/inventory-service');
const {inspectSchema,assertTransactional}=require('../lib/schema-check');
const {workbook,letter,xml}=require('../lib/xlsx');
const JSZip=require('../vendor/jszip.min.js');
const auth=require('../lib/auth');
const A={ProductVariantId:1,Marca:'Marca Á',Modelo:'Aurora',Category:'Natural',Color:'Miel',Power:-1.5,PowerLabel:'-1.50',Stock:7,Price:200,ScanCode:'000123',ProductStatus:'Activo',VariantStatus:'Activo'};
const B={...A,ProductVariantId:2,Marca:'Marca B',Power:0,Color:'Azul',PowerLabel:'Sin graduación'};
function fakeConnection(handler=()=>[[]]){
 const calls=[];
 const c={calls,execute:async(sql,args=[])=>{calls.push([sql,args]);if(sql.includes('GET_LOCK'))return [[{Acquired:1}]];if(sql.includes('RELEASE_LOCK'))return [[{Released:1}]];return handler(sql,args);},query:async(sql,args)=>{calls.push([sql,args]);return handler(sql,args);},beginTransaction:async()=>calls.push(['BEGIN']),commit:async()=>calls.push(['COMMIT']),rollback:async()=>calls.push(['ROLLBACK']),release:()=>calls.push(['RELEASE']),destroy:()=>calls.push(['DESTROY'])};
 return c;
}
test('códigos conservan ceros iniciales y recortan solo extremos',()=>{assert.equal(codeValue(' 00001234 '),'00001234');assert.throws(()=>codeValue(''));assert.throws(()=>codeValue(1234));assert.throws(()=>codeValue('ABC\u0000DEF'));});
test('cantidad: enteros positivos, sin cero, decimales, NaN ni booleanos',()=>{assert.equal(positiveInteger('12'),12);for(const x of [0,-1,'',null,true,'2.5',NaN,'Infinity',1000001])assert.throws(()=>positiveInteger(x),undefined,String(x));});
test('validación de identificadores y marca',()=>{const id=randomUUID();assert.equal(requestKey(id.toUpperCase()),id);assert.throws(()=>requestKey('id-falso'));assert.equal(sameBrand(' Marca Á ','marca a'),true);assert.equal(sameBrand('A','B'),false);});
test('las notas aceptan varias líneas; los códigos no',()=>{assert.equal(text('primera\nsegunda',2000,true),'primera\nsegunda');assert.throws(()=>codeValue('A\nB'));assert.throws(()=>text('a\u0000b',100,true));});
test('filtros OR entre marcas, AND con color y graduación',()=>{const f={brands:['marca a','Marca B'],powers:['-1.5'],colors:['miel']};assert.equal(matchesProduct(A,f),true);assert.equal(matchesProduct(B,f),false);assert.equal(matchesProduct(A,{...f,brands:['Marca C']}),false);});
test('con y sin graduación distinguen los pendientes',()=>{assert.equal(matchesProduct(A,{powerType:'graduated'}),true);assert.equal(matchesProduct(B,{powerType:'none'}),true);assert.equal(matchesProduct(B,{powerType:'graduated'}),false);assert.equal(matchesProduct({...B,NeedsReview:1},{powerType:'none'}),false);assert.equal(matchesProduct({...B,NeedsReview:1},{status:'pending'}),true);});
test('buscador combina palabras, códigos, categoría y estado',()=>{assert.equal(matchesProduct(A,{search:'aurora 000123 miel'}),true);assert.equal(matchesProduct(A,{search:'aurora verde'}),false);assert.equal(matchesProduct({...A,Stock:0},{stockMode:'with_stock'}),false);assert.equal(matchesProduct({...A,ProductStatus:'Inactivo'},{status:'active'}),false);});
test('categorías normalizadas sin confundir Premium con Muñeca',()=>{assert.equal(categoryKey('Muñeca'),'muneca');assert.equal(categoryKey('Halloween / fantasía'),'halloween');assert.equal(categoryKey('Premium'),'premium');assert.deepEqual(filtersFromQuery({brands:['A','B'],colors:'Azul'}).brands,['A','B']);});
test('consolidado incluye no contados y omite capturas anuladas',()=>{const base=[{ProductVariantId:1,StockBefore:10},{ProductVariantId:2,StockBefore:3}];const lines=[{ProductVariantId:1,Quantity:2,StockAfter:2},{ProductVariantId:1,Quantity:5,StockAfter:7},{ProductVariantId:1,Quantity:1,VoidedAt:'2026-01-01'}];const result=consolidated(base,lines,'STOCKTAKE');assert.equal(result[0].Quantity,7);assert.equal(result[0].Difference,-3);assert.equal(result[0].Voided,1);assert.equal(result[1].CountStatus,'Sin contar');assert.equal(result[1].Difference,-3);});
test('entradas conservan el stock anterior de la primera captura',()=>{const rows=consolidated([],[{ProductVariantId:3,StockBefore:12,StockAfter:15,Quantity:3},{ProductVariantId:3,StockBefore:15,StockAfter:17,Quantity:2}],'RECEIPT');assert.equal(rows[0].StockBefore,12);assert.equal(rows[0].Quantity,5);assert.equal(rows[0].LastRecordedStock,17);});
test('transacción confirma y libera el bloqueo en orden',async()=>{const c=fakeConnection();assert.equal(await transaction({getConnection:async()=>c},async()=>42),42);assert.deepEqual(c.calls.map(x=>x[0].split(' ')[0]),['SELECT','BEGIN','COMMIT','SELECT','RELEASE']);});
test('una falla revierte; no confirma una suma parcial',async()=>{const c=fakeConnection();await assert.rejects(()=>transaction({getConnection:async()=>c},async()=>{throw new Error('prueba');}),/prueba/);assert.ok(c.calls.some(x=>x[0]==='ROLLBACK'));assert.ok(!c.calls.some(x=>x[0]==='COMMIT'));assert.equal(c.calls.at(-1)[0],'RELEASE');});
test('si falla liberar GET_LOCK se destruye la conexión, no vuelve al pool',async()=>{const c=fakeConnection();const old=c.execute;c.execute=async(sql,args)=>{if(sql.includes('RELEASE_LOCK'))throw new Error('red');return old(sql,args);};await transaction({getConnection:async()=>c},async()=>1);assert.ok(c.calls.some(x=>x[0]==='DESTROY'));assert.ok(!c.calls.some(x=>x[0]==='RELEASE'));});
test('una marca pausada sigue protegida de modificaciones ajenas',async()=>{const c=fakeConnection(()=>[[{Id:'otro',Brand:'Marca A',Folio:'INV-1',Status:'PAUSED'}]]);await assert.rejects(()=>assertBrandUnlocked(c,'Marca A'),e=>e.code==='BRAND_LOCKED');assert.match(c.calls[0][0],/ACTIVE','PAUSED/);});
test('el preflight transaccional rechaza motores no InnoDB',async()=>{const names=['Products','ProductVariants','CLInventorySessions','CLInventoryBaseline','CLInventoryLines','CLInventoryDrafts','CLInventoryEvents'];const c=fakeConnection(()=>[names.map(TABLE_NAME=>({TABLE_NAME,ENGINE:TABLE_NAME==='Products'?'MyISAM':'InnoDB'}))]);await assert.rejects(()=>assertTransactional(c),e=>e.code==='SCHEMA_NOT_READY');});
test('Excel válido, códigos como texto, fórmulas solo controladas por la aplicación',async()=>{const buf=await workbook([{name:'Inventario',columns:[{key:'code',title:'Código',type:'text'},{key:'stock',title:'Cantidad',type:'number'},{key:'value',title:'Valor',type:'money',value:(r,n)=>({formula:`B${n}*2`,result:r.stock*2})}],rows:[{code:'0000123',stock:4},{code:'=HYPERLINK("x")',stock:3}],totals:['stock','value']}]);assert.equal(buf.subarray(0,2).toString(),'PK');const zip=await JSZip.loadAsync(buf);const sheet=await zip.file('xl/worksheets/sheet1.xml').async('string');assert.match(sheet,/0000123/);assert.match(sheet,/<f>B6\*2<\/f>/);assert.match(sheet,/t="inlineStr"><is><t xml:space="preserve">=HYPERLINK/);assert.match(sheet,/<f>SUM\(B6:B7\)<\/f><v>7<\/v>/);assert.match(sheet,/state="frozen"/);assert.ok(zip.file('[Content_Types].xml'));});
test('Excel de una columna no crea merges inválidos',async()=>{const z=await JSZip.loadAsync(await workbook([{name:'Una',columns:[{key:'a',title:'A'}],rows:[]} ]));const s=await z.file('xl/worksheets/sheet1.xml').async('string');assert.ok(!s.includes('mergeCells'));assert.equal(letter(26),'AA');assert.equal(xml('<a>&'), '&lt;a&gt;&amp;');});
test('autenticación rechaza falta de token y verifica el estado actual del usuario',async()=>{process.env.JWT_SECRET='solo-pruebas-aleatorias-de-32-caracteres';let status='Activo';const {createToken,verifyToken}=auth({execute:async()=>[[{Id:1,Username:'admin',FullName:'Prueba',Role:'ADMIN',Status:status}]]});function res(){return {statusCode:200,status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;}};}let next=0,r=res();await verifyToken({headers:{}},r,()=>next++);assert.equal(r.statusCode,401);const token=createToken({Id:1,Username:'admin',FullName:'Prueba',Role:'ADMIN'});const req={headers:{authorization:'Bearer '+token}};r=res();await verifyToken(req,r,()=>next++);assert.equal(next,1);assert.equal(req.user.username,'admin');status='Inactivo';r=res();await verifyToken(req,r,()=>next++);assert.equal(r.statusCode,403);assert.equal(next,1);});
