import { useMemo,useState,useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Search,SlidersHorizontal,X,ChevronLeft,ChevronRight } from 'lucide-react';
import Navbar from '../components/Navbar';import Sidebar from '../components/Sidebar';import BottomNav from '../components/BottomNav';import WhatsAppButton from '../components/WhatsAppButton';import SiteFooter from '../components/SiteFooter';
import LensCard from '../components/LensCard';import ProductQuickView from '../components/ProductQuickView';import ProductFilters,{emptyFilters,categoryLabel,powerLabel} from '../components/ProductFilters';import Modal from '../components/Modal';
import { useCatalog,groupProducts } from '../utils/catalog';import { matchesProduct,categoryKey } from '../utils/productFilters';import { queryString } from '../utils/api';
const SIZE=12;
export default function Catalog(){
 const [sp,setSp]=useSearchParams(),[menu,setMenu]=useState(false),[mobileFilters,setMobileFilters]=useState(false),[selected,setSelected]=useState(null),[page,setPage]=useState(1),[sort,setSort]=useState('available');
 const {products,loading,error,retry}=useCatalog();
 const filters=useMemo(()=>({...emptyFilters,search:sp.get('q') || sp.get('search') || '',brands:sp.getAll('brands'),categories:sp.getAll('categories').length?sp.getAll('categories'):sp.get('category')?[sp.get('category')]:[],colors:sp.getAll('colors'),powers:sp.getAll('powers'),powerType:sp.get('powerType') || 'all',stockMode:sp.get('stockMode') || 'all'}),[sp]);
 const change=f=>setSp(queryString(f),{replace:true});
 useEffect(()=>{setPage(1)},[sp,sort]);
 const options=useMemo(()=>{const unique=k=>[...new Set(products.map(p=>p[k]).filter(v=>v!==''&&v!=null))].sort((a,b)=>String(a).localeCompare(String(b),'es'));return{brands:unique('Marca'),colors:unique('Color'),categories:[...new Set(['natural','muneca','halloween',...products.map(p=>categoryKey(p.Category)).filter(Boolean)])],powers:unique('Power').map(Number).sort((a,b)=>b-a)}},[products]);
 const found=useMemo(()=>{
  // Primero filtrar las variantes y DESPUÉS agrupar; no descarta productos solo graduados.
  const grouped=groupProducts(products.filter(p=>matchesProduct(p,filters)));
  return grouped.sort((a,b)=>sort==='price-asc'?a.MinPrice-b.MinPrice:sort==='price-desc'?b.MinPrice-a.MinPrice:sort==='name'?`${a.Marca} ${a.Modelo}`.localeCompare(`${b.Marca} ${b.Modelo}`,'es'):(b.TotalStock>0)-(a.TotalStock>0)||Number(b.ProductVariantId)-Number(a.ProductVariantId));
 },[products,filters,sort]);
 const pages=Math.max(1,Math.ceil(found.length/SIZE)),safe=Math.min(page,pages),shown=found.slice((safe-1)*SIZE,safe*SIZE);
 const chips=[...filters.brands.map(v=>({key:'brands',v,label:v})),...filters.categories.map(v=>({key:'categories',v,label:categoryLabel(v)})),...filters.colors.map(v=>({key:'colors',v,label:v})),...filters.powers.map(v=>({key:'powers',v,label:powerLabel(v)}))];
 return <div className="app cl-storefront"><Navbar setIsOpen={setMenu}/><Sidebar isOpen={menu} setIsOpen={setMenu}/><main className="cl-catalog-main"><header className="cl-catalog-heading"><span className="cl-eyebrow">EL COLOR ES SOLO EL COMIENZO</span><h1>Encuentra <em>tu mirada.</em></h1><p>Combina marcas, estilos, colores y graduaciones. Tu próximo favorito está aquí.</p></header>
 <div className="cl-catalog-toolbar"><div className="cl-search"><Search size={20}/><input aria-label="Buscar lentes" placeholder="Buscar por marca, modelo, color o código…" value={filters.search} onChange={e=>change({...filters,search:e.target.value})}/>{filters.search&&<button aria-label="Limpiar búsqueda" onClick={()=>change({...filters,search:''})}><X size={18}/></button>}</div><button className="cl-button cl-mobile-filter-button" onClick={()=>setMobileFilters(true)}><SlidersHorizontal size={18}/>Filtros{chips.length?` (${chips.length})`:''}</button><label className="cl-sort">Ordenar<select aria-label="Orden del catálogo" value={sort} onChange={e=>setSort(e.target.value)}><option value="available">Disponibles primero</option><option value="price-asc">Precio: menor a mayor</option><option value="price-desc">Precio: mayor a menor</option><option value="name">Marca y modelo</option></select></label></div>
 <div className="cl-catalog-layout"><aside className="cl-filter-sidebar"><div className="cl-filter-title"><h2><SlidersHorizontal size={18}/>Filtrar</h2><button className="cl-text-btn" onClick={()=>change(emptyFilters)}>Limpiar</button></div><ProductFilters filters={filters} onChange={change} options={options}/></aside><section className="cl-catalog-results"><div className="cl-results-heading"><span><strong>{found.length}</strong> modelos / colores encontrados</span><small>Mostrando {found.length?(safe-1)*SIZE+1:0}–{Math.min(safe*SIZE,found.length)}</small></div>{chips.length>0&&<div className="cl-filter-chips">{chips.map(c=><button key={c.key+c.v} onClick={()=>change({...filters,[c.key]:filters[c.key].filter(v=>v!==c.v)})}>{c.label}<X size={13}/></button>)}</div>}
 {loading?<div className="cl-loading-grid">{[0,1,2].map(n=><div className="cl-skeleton" key={n}/>)}</div>:error?<div className="cl-empty" role="alert"><h3>No pudimos cargar los lentes</h3><p>{error}</p><button className="cl-button" onClick={retry}>Reintentar</button></div>:shown.length?<div className="cl-products-grid cl-catalog-products">{shown.map(p=><LensCard key={`${p.ProductId}-${p.Color}`} product={p} onOpen={setSelected}/>)}</div>:<div className="cl-empty"><Search size={30}/><h3>No encontramos esa combinación</h3><p>Prueba otro color o quita alguna marca o graduación.</p><button className="cl-button" onClick={()=>change(emptyFilters)}>Limpiar filtros</button></div>}
 {pages>1&&<nav className="cl-pagination" aria-label="Páginas del catálogo"><button className="cl-icon-btn" disabled={safe===1} aria-label="Página anterior" onClick={()=>setPage(p=>p-1)}><ChevronLeft size={19}/></button><span>{safe} / {pages}</span><button className="cl-icon-btn" disabled={safe===pages} aria-label="Página siguiente" onClick={()=>setPage(p=>p+1)}><ChevronRight size={19}/></button></nav>}</section></div>
 </main><SiteFooter/><BottomNav/><WhatsAppButton/>{selected&&<ProductQuickView product={selected} onClose={()=>setSelected(null)}/>} {mobileFilters&&<Modal title="Encuentra tu combinación" onClose={()=>setMobileFilters(false)}><ProductFilters filters={filters} onChange={change} options={options}/><div className="cl-modal-actions"><button className="cl-button" onClick={()=>change(emptyFilters)}>Limpiar</button><button className="cl-button cl-button-dark" onClick={()=>setMobileFilters(false)}>Ver {found.length} modelos</button></div></Modal>}</div>;
}
