import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowDownToLine, ArrowLeft, ArrowRight, Boxes, CheckCircle2, ClipboardCheck, PackagePlus, Pause, Play, ScanLine, Search, Trash2, TriangleAlert } from 'lucide-react';
import AdminSidebar from '../../components/AdminSidebar';
import Modal from '../../components/Modal';
import InventoryCapture from '../../components/inventory/InventoryCapture';
import { request, downloadExcel, queryString, uuid } from '../../utils/api';
const labels={ACTIVE:'En curso',PAUSED:'En pausa',COMPLETED:'Finalizado',RECEIPT:'Entrada de mercancía',STOCKTAKE:'Inventario completo'};
const date=v=>v?new Date(/[zZ]|[+]\d\d/.test(String(v))?v:String(v).replace(' ','T')+'Z').toLocaleString('es-MX'): '—';
const num=v=>Number(v||0).toLocaleString('es-MX');
const initialFilters={kind:'',status:'',search:'',from:'',to:'',page:1};
export default function InventoryAdmin(){
 const {sessionId}=useParams(),navigate=useNavigate();
 const [meta,setMeta]=useState({brands:[],openStocktakes:[],pending:0,stats:[]}),[history,setHistory]=useState({sessions:[],total:0,pageSize:25});
 const [filters,setFilters]=useState(initialFilters),[detail,setDetail]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[scan,setScan]=useState(false),[setup,setSetup]=useState(false),[brand,setBrand]=useState('');
 const [preview,setPreview]=useState(null),[confirmation,setConfirmation]=useState(null),[tab,setTab]=useState('products'),[tableSearch,setTableSearch]=useState('');
 const [reference,setReference]=useState(''),[notes,setNotes]=useState(''),[editing,setEditing]=useState(false);
 const [categories,setCategories]=useState([]),[allCategories,setAllCategories]=useState(false),[graduation,setGraduation]=useState('PLANO');
 const autoScan=useRef(false);
 const [pendingStart,setPendingStart]=useState(()=>{try{return JSON.parse(localStorage.getItem('cl-inventory-start-pending')||'null')}catch{return null}});
 async function refreshMeta(){const m=await request('/api/inventory/meta');setMeta(m);}
 async function refreshDetail(){if(!sessionId)return;const d=await request(`/api/inventory/sessions/${sessionId}`);setDetail(d);setReference(d.session.Reference||'');setNotes(d.session.Notes||'');return d;}
 useEffect(()=>{refreshMeta().catch(e=>setError(e.message));},[]);
 useEffect(()=>{let live=true;setLoading(true);setError('');setDetail(null);setTab('products');setTableSearch('');setScan(false);if(!sessionId){setLoading(false);return;}
 request(`/api/inventory/sessions/${sessionId}`).then(d=>{if(live){setDetail(d);setReference(d.session.Reference||'');setNotes(d.session.Notes||'');if(autoScan.current&&d.session.Status==='ACTIVE'){setScan(true);autoScan.current=false;}}}).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false;};},[sessionId]);
 useEffect(()=>{if(sessionId)return;let live=true;setLoading(true);const timeout=setTimeout(()=>request('/api/inventory/sessions?'+queryString(filters)).then(h=>live&&setHistory(h)).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false)),200);return()=>{live=false;clearTimeout(timeout);};},[sessionId,filters]);
 async function createSession(kind,recover=false){
  setBusy(true);setError('');try{
   // Una operación incierta siempre se reintenta con la misma clave, incluso tras recargar.
   const existing=localStorage.getItem('cl-inventory-start-pending');
   let payload=existing?JSON.parse(existing):null;
   if(payload&&!recover)throw new Error('Hay un inicio pendiente de confirmar. Usa Recuperar folio pendiente para recuperar el alcance original antes de iniciar otro conteo.');
   if(!payload){payload={kind,brand:kind==='STOCKTAKE'?preview.brand:null,...(kind==='STOCKTAKE'?{scope:preview.scope}:{}),confirmReset:kind==='STOCKTAKE',requestKey:uuid()};localStorage.setItem('cl-inventory-start-pending',JSON.stringify(payload));setPendingStart(payload);}
   const result=await request('/api/inventory/sessions',{method:'POST',body:payload});
   localStorage.removeItem('cl-inventory-start-pending');setPendingStart(null);setSetup(false);setPreview(null);autoScan.current=true;navigate('/admin/inventory/'+result.session.Id);await refreshMeta();
  }catch(e){if(e.status>=400&&e.status<500){localStorage.removeItem('cl-inventory-start-pending');setPendingStart(null);}setError(e.message);}finally{setBusy(false);}
 }
 async function getPreview(){setBusy(true);setError('');try{setPreview(await request('/api/inventory/preview?'+queryString({brand,allCategories,categories,graduation})));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function status(status,confirmUncounted=false){setBusy(true);setError('');try{await request(`/api/inventory/sessions/${sessionId}/status`,{method:'PATCH',body:{status,confirmUncounted}});setConfirmation(null);await refreshDetail();await refreshMeta();setNotice(status==='PAUSED'?'Avance guardado. Puedes cerrar el sistema y continuar otro día.':status==='COMPLETED'?'Inventario finalizado. Su historial y Excel quedan disponibles.':'Inventario reanudado. No se volvió a poner el stock en cero.');if(status==='ACTIVE')setScan(true);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function exportFile(path,name){setBusy(true);setError('');try{await downloadExcel(path,name);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function saveMetadata(){setBusy(true);setError('');try{await request(`/api/inventory/sessions/${sessionId}/metadata`,{method:'PATCH',body:{reference,notes}});await refreshDetail();setEditing(false);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function voidLine(line){if(!window.confirm(`¿Anular la captura de ${line.Quantity} unidades del código ${line.Code}? Se restarán esas unidades y quedará registro de la corrección.`))return;setBusy(true);setError('');try{await request(`/api/inventory/sessions/${sessionId}/lines/${line.Id}`,{method:'DELETE'});await refreshDetail();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const s=detail?.session,summary=detail?.summary;
 const categoryOptions=[...new Set((meta.brandCategories||[]).filter(p=>p.Marca.trim().localeCompare(brand.trim(),'es',{sensitivity:'base'})===0).map(p=>p.Category.trim()))];
 const rows=(tab==='products'?detail?.products:detail?.lines)?.filter(p=>[p.Code,p.Marca,p.Modelo,p.Color,p.PowerLabel].join(' ').toLowerCase().includes(tableSearch.toLowerCase()))||[];
 return <div className="admin-page cl-admin"><AdminSidebar/><main className="admin-content cl-admin-content">
  <header className="cl-page-heading"><div><span className="cl-eyebrow">ADMINISTRACIÓN / INVENTARIO</span><h1>{s?s.Folio:'Cada pieza, en su lugar.'}</h1><p>{s?`${labels[s.Kind]} · ${s.Brand||'Varias marcas'}${s.ScopeLabel?' · '+s.ScopeLabel:''}`:'Recibe mercancía, realiza conteos físicos y conserva la trazabilidad de tu stock.'}</p></div>{sessionId?<button className="cl-btn cl-btn-light" onClick={()=>navigate('/admin/inventory')}><ArrowLeft size={17}/> Historial</button>:<Link className="cl-btn cl-btn-light" to="/admin/reports/products"><ArrowDownToLine size={17}/> Reporte de existencias</Link>}</header>
  {error&&<div className="cl-alert cl-alert-danger" role="alert"><TriangleAlert size={19}/><span>{error}</span><button onClick={()=>setError('')} aria-label="Cerrar error">×</button></div>}
  {notice&&<div className="cl-alert cl-alert-success" role="status"><CheckCircle2 size={19}/><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="Cerrar aviso">×</button></div>}
  {!sessionId&&pendingStart&&<div className="cl-alert" role="alert"><TriangleAlert size={20}/><div><strong>Hay un inicio pendiente de confirmar</strong><p>{labels[pendingStart.kind]} · {pendingStart.brand||'Varias marcas'}. Recupera el folio original antes de iniciar otro inventario.</p><button className="cl-btn cl-btn-light" disabled={busy} onClick={()=>createSession(pendingStart.kind,true)}>Recuperar folio pendiente</button></div></div>}
  {!sessionId&&<><div className="cl-inventory-choices">
   <section className="cl-operation-card"><span className="cl-operation-icon"><PackagePlus/></span><span className="cl-eyebrow">01 / RECIBIR</span><h2>Entrada de mercancía</h2><p>Escanea cada código y agrega la cantidad que llegó. Las unidades se suman al stock actual, sin borrar existencias.</p><button disabled={busy} className="cl-btn" onClick={()=>createSession('RECEIPT')}><ScanLine size={18}/> Nueva entrada <ArrowRight size={17}/></button><small>Marca automática para productos registrados.</small></section>
   <section className="cl-operation-card cl-operation-count"><span className="cl-operation-icon"><ClipboardCheck/></span><span className="cl-eyebrow">02 / CONTAR DESDE CERO</span><h2>Inventario completo</h2><p>Elige una marca, las categorías y la graduación que vas a contar. Solo ese alcance se reinicia a cero. Puedes pausar y continuar después.</p><button disabled={busy} className="cl-btn cl-btn-dark" onClick={()=>{setSetup(true);setPreview(null);}}><Boxes size={18}/> Elegir alcance <ArrowRight size={17}/></button><small>Las existencias fuera del alcance se conservan.</small></section>
  </div>
  {!!meta.openStocktakes.length&&<div className="cl-alert"><Pause size={20}/><div><strong>Marcas en inventario</strong><p>Para evitar diferencias, no se permiten ventas, entradas ni edición de stock de estas marcas hasta finalizar el conteo.</p><div className="cl-inline-links">{meta.openStocktakes.map(v=><Link key={v.Id} to={'/admin/inventory/'+v.Id}>{v.Brand} · {v.ScopeLabel} · {labels[v.Status]} <ArrowRight size={14}/></Link>)}</div></div></div>}
  {meta.pending>0&&<Link className="cl-pending-link" to="/admin/products?view=pending"><TriangleAlert size={18}/>{num(meta.pending)} productos por completar en Productos <ArrowRight size={16}/></Link>}
  <section className="cl-panel"><div className="cl-panel-heading"><div><h2>Historial de inventarios</h2><p>Entradas y conteos guardados, incluso los que siguen en pausa.</p></div><button disabled={busy||!history.total} className="cl-btn cl-btn-light" onClick={()=>exportFile('/api/inventory/sessions/export?'+queryString(filters),'ColorLenses-Historial.xlsx')}><ArrowDownToLine size={17}/> Exportar historial</button></div>
  <div className="cl-history-filters"><label className="cl-search"><Search size={18}/><input placeholder="Folio, marca o referencia" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value,page:1})}/></label><select aria-label="Tipo de inventario" value={filters.kind} onChange={e=>setFilters({...filters,kind:e.target.value,page:1})}><option value="">Todos los tipos</option><option value="RECEIPT">Entradas</option><option value="STOCKTAKE">Inventarios completos</option></select><select aria-label="Estado" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value,page:1})}><option value="">Todos los estados</option>{['ACTIVE','PAUSED','COMPLETED'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select><label>Desde (UTC)<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value,page:1})}/></label><label>Hasta (UTC)<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value,page:1})}/></label></div>
  <div className="cl-table-wrap"><table className="cl-data-table"><thead><tr><th>Folio / referencia</th><th>Tipo / marca</th><th>Estado</th><th>Variantes</th><th>Unidades</th><th>Fecha local</th><th>Acciones</th></tr></thead><tbody>{history.sessions.map(h=><tr key={h.Id}><td><Link className="cl-table-link" to={'/admin/inventory/'+h.Id}>{h.Folio}</Link><small>{h.Reference||'Sin referencia'}</small></td><td>{labels[h.Kind]}<small>{h.Brand||'Varias marcas'}</small>{h.ScopeLabel&&<small>{h.ScopeLabel}</small>}</td><td><span className={'cl-status cl-status-'+h.Status.toLowerCase()}>{labels[h.Status]}</span></td><td>{num(h.TotalProducts)}</td><td><strong>{num(h.TotalUnits)}</strong></td><td>{date(h.CreatedAt)}</td><td><div className="cl-table-actions"><Link to={'/admin/inventory/'+h.Id}>Abrir</Link><button disabled={busy} onClick={()=>exportFile(`/api/inventory/sessions/${h.Id}/export`,h.Folio+'.xlsx')} aria-label={'Exportar '+h.Folio}><ArrowDownToLine size={17}/></button></div></td></tr>)}</tbody></table></div>
  {loading?<p className="cl-empty">Cargando historial…</p>:!history.total&&<div className="cl-empty"><ClipboardCheck size={30}/><h3>Todavía no hay registros</h3><p>Tu primera entrada o inventario aparecerá aquí.</p></div>}
  <div className="cl-pagination"><span>{num(history.total)} registros</span><button disabled={filters.page<=1} onClick={()=>setFilters({...filters,page:filters.page-1})}>Anterior</button><span>{filters.page} / {Math.max(1,Math.ceil(history.total/25))}</span><button disabled={filters.page*25>=history.total} onClick={()=>setFilters({...filters,page:filters.page+1})}>Siguiente</button></div></section></>}
  {sessionId&&loading&&<div className="cl-panel cl-empty">Cargando inventario…</div>}
  {s&&<><div className="cl-session-bar"><div><span className={'cl-status cl-status-'+s.Status.toLowerCase()}>{labels[s.Status]}</span><span>Creado por {s.CreatedByName} · {date(s.CreatedAt)}</span></div><div className="cl-button-row">{s.Status==='ACTIVE'&&<><button className="cl-btn" disabled={busy} onClick={()=>setScan(true)}><ScanLine size={18}/> Escanear / agregar</button><button className="cl-btn cl-btn-light" disabled={busy} onClick={()=>status('PAUSED')}><Pause size={17}/> Pausar</button></>}{s.Status==='PAUSED'&&<button className="cl-btn" disabled={busy} onClick={()=>status('ACTIVE')}><Play size={17}/> Continuar</button>}{s.Status!=='COMPLETED'&&<button className="cl-btn cl-btn-dark" disabled={busy} onClick={()=>setConfirmation('finish')}><CheckCircle2 size={17}/> Finalizar</button>}<button className="cl-btn cl-btn-light" disabled={busy} onClick={()=>exportFile(`/api/inventory/sessions/${sessionId}/export`,s.Folio+'.xlsx')}><ArrowDownToLine size={17}/> Excel</button></div></div>
  {s.Kind==='STOCKTAKE'&&<div className="cl-alert"><ClipboardCheck size={20}/><div><strong>Alcance: {s.ScopeLabel}</strong><p>{s.LegacyScope?'Este folio se inició con la regla anterior y abarca toda la marca. El parche no recupera existencias que ya se reiniciaron.':'Solo se ajustan las existencias de este alcance; las demás se conservan. El alcance no cambia al pausar o continuar.'}</p></div></div>}
    {s.Status==='PAUSED'&&<div className="cl-alert"><Pause size={18}/><span>El avance está guardado en la base de datos. Continuar retoma este mismo folio sin reiniciar el stock.{s.Kind==='STOCKTAKE'?' La marca permanece bloqueada para ventas y cambios hasta finalizar.':''}</span></div>}
  <div className="cl-metric-grid"><article><span>{s.Kind==='STOCKTAKE'?'Unidades contadas':'Unidades recibidas'}</span><strong>{num(summary.TotalUnits)}</strong><small>{num(summary.TotalScans)} capturas aplicadas</small></article><article><span>Variantes registradas</span><strong>{num(summary.TotalProducts)}</strong><small>Consolidado por código / variante</small></article>{s.Kind==='STOCKTAKE'?<><article><span>Unidades antes de reiniciar</span><strong>{num(summary.OriginalUnits)}</strong><small>Registro del stock anterior</small></article><article><span>Variantes sin contar</span><strong>{num(summary.Uncounted)}</strong><small>Solo dentro de este alcance</small></article></>:<article><span>Códigos nuevos</span><strong>{num(summary.PendingProducts)}</strong><small>Pendientes de completar al capturar</small></article>}</div>
  <section className="cl-panel cl-reference"><div><strong>Referencia / proveedor</strong><p>{s.Reference||'Sin referencia'}{s.Notes&&<><br/>{s.Notes}</>}</p></div>{s.Status!=='COMPLETED'&&<button className="cl-btn cl-btn-light" onClick={()=>setEditing(true)}>Editar referencia</button>}</section>
  <section className="cl-panel"><div className="cl-panel-heading"><div className="cl-tabs"><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}>Productos</button><button className={tab==='movements'?'active':''} onClick={()=>setTab('movements')}>Capturas / correcciones</button></div><label className="cl-search"><Search size={17}/><input placeholder="Buscar en este inventario" value={tableSearch} onChange={e=>setTableSearch(e.target.value)}/></label></div>
  <div className="cl-table-wrap"><table className="cl-data-table"><thead><tr><th>Código / producto</th><th>Marca</th><th>Color / graduación</th><th>Antes</th><th>{tab==='products'?(s.Kind==='STOCKTAKE'?'Contado':'Recibido'):'Cantidad'}</th><th>{tab==='products'&&s.Kind==='STOCKTAKE'?'Diferencia':'Stock al registrar'}</th><th>Estado</th>{tab==='movements'&&<th>Acciones</th>}</tr></thead><tbody>{rows.map((p,i)=><tr key={tab==='products'?p.ProductVariantId:p.Id} className={p.VoidedAt?'cl-voided':''}><td><code>{p.Code}</code><small>{p.Modelo}</small></td><td>{p.Marca}</td><td>{p.Color||'Por confirmar'}<small>{p.PowerLabel||'Por confirmar'}</small></td><td>{num(p.StockBefore)}</td><td><strong>{num(p.Quantity)}</strong></td><td>{num(tab==='products'?(s.Kind==='STOCKTAKE'?p.Difference:p.LastRecordedStock):p.StockAfter)}</td><td>{tab==='products'?<span className={'cl-status '+(p.Counted?'cl-status-completed':'cl-status-paused')}>{s.Kind==='STOCKTAKE'?p.CountStatus:(p.Counted?'Recibido':'Anulado')}</span>:<><span className={'cl-status '+(p.VoidedAt?'cl-status-voided':'cl-status-completed')}>{p.VoidedAt?'Anulado':'Aplicado'}</span><small>{date(p.CreatedAt)} · {p.CreatedByName}</small></>}{Number(p.NeedsReview)>0&&<small>Código nuevo al capturar</small>}</td>{tab==='movements'&&<td>{s.Status==='ACTIVE'&&!p.VoidedAt&&<button className="cl-icon-btn" disabled={busy} aria-label={'Anular captura '+p.Id} onClick={()=>voidLine(p)}><Trash2 size={17}/></button>}</td>}</tr>)}</tbody></table></div>{!rows.length&&<div className="cl-empty"><ScanLine size={30}/><h3>{tableSearch?'Sin coincidencias':'Listo para tu primera captura'}</h3><p>Escanea un código o introdúcelo manualmente.</p></div>}
  <p className="cl-table-note">{s.Kind==='STOCKTAKE'?'La diferencia compara el conteo con el stock guardado antes del reinicio.':'El stock al registrar es una fotografía de ese momento; no incluye ventas ni movimientos posteriores.'} Los movimientos anulados permanecen en el historial.</p></section></>}
  {setup&&<Modal title={preview?'Confirmar alcance del inventario':'Elegir alcance del inventario'} onClose={()=>{if(!busy){setSetup(false);setPreview(null);}}} busy={busy}>
   {preview?<><div className="cl-alert cl-alert-danger"><TriangleAlert size={24}/><div><strong>{preview.brand} · {preview.scopeLabel}</strong><p>Se pondrá en cero únicamente este alcance: {num(preview.variants)} variantes · {num(preview.units)} unidades.</p></div></div><p>Se guardará el stock anterior para compararlo con tu conteo. Las categorías y graduaciones fuera de esta selección conservarán sus existencias.</p><p>Mientras cuentes, la marca <strong>{preview.brand}</strong> permanecerá bloqueada para ventas y cambios. Solo las variantes de este alcance que no cuentes quedarán en cero.</p>{!preview.variants&&<p className="cl-form-error">No hay variantes con esta selección. Vuelve y elige otro alcance.</p>}<div className="cl-button-row"><button className="cl-btn cl-btn-light" disabled={busy} onClick={()=>setPreview(null)}>Volver</button><button className="cl-btn cl-btn-danger" disabled={busy||!preview.variants} onClick={()=>createSession('STOCKTAKE')}>{busy?'Iniciando…':'Sí, reiniciar solo este alcance'}</button></div></>:<><p>Selecciona lo que vas a contar físicamente. Para contar naturales sin afectar los graduados, elige Natural y Sin graduación.</p><label className="cl-field">Marca<select aria-label="Marca a inventariar" value={brand} disabled={busy} onChange={e=>{setBrand(e.target.value);setCategories([]);setAllCategories(false);setGraduation('PLANO');}}><option value="">Selecciona una marca</option>{meta.brands.map(b=><option key={b}>{b}</option>)}</select></label>
   {brand&&<><fieldset className="cl-inventory-scope"><legend>Categorías de {brand}</legend><label className="cl-check"><input type="checkbox" checked={allCategories} disabled={busy} onChange={e=>{setAllCategories(e.target.checked);setCategories([]);}}/>Todas las categorías</label>{categoryOptions.map(category=><label className="cl-check" key={category}><input type="checkbox" checked={allCategories||categories.includes(category)} disabled={busy||allCategories} onChange={e=>setCategories(current=>e.target.checked?[...current,category]:current.filter(c=>c!==category))}/>{category}</label>)}{!categoryOptions.length&&<small>Esta marca todavía no tiene categorías registradas.</small>}</fieldset>
   <label className="cl-field">Graduación<select aria-label="Graduación a inventariar" value={graduation} disabled={busy} onChange={e=>setGraduation(e.target.value)}><option value="PLANO">Sin graduación</option><option value="PRESCRIPTION">Con graduación</option><option value="ALL">Todas las graduaciones</option></select><small>Con graduación incluye las potencias distintas de cero. Los productos con graduación por confirmar se conservan al elegir con o sin graduación.</small></label></>}
   <button className="cl-btn cl-full" disabled={!brand||(!allCategories&&!categories.length)||busy} onClick={getPreview}>{busy?'Revisando…':'Revisar alcance'}<ArrowRight size={17}/></button></>}{error&&<p className="cl-form-error" role="alert">{error}</p>}
  </Modal>}
  {confirmation==='finish'&&s&&<Modal title="Finalizar inventario" busy={busy} onClose={()=>setConfirmation(null)}><p>Se cerrará <strong>{s.Folio}</strong> con <strong>{num(summary.TotalUnits)} unidades</strong> registradas. Después podrás consultarlo y exportarlo, pero no modificar sus capturas.</p>{s.Kind==='STOCKTAKE'&&<p><strong>Alcance:</strong> {s.Brand} · {s.ScopeLabel}. Las existencias fuera de este alcance se conservan.</p>}{s.Kind==='STOCKTAKE'&&summary.Uncounted>0&&<div className="cl-alert cl-alert-danger"><TriangleAlert/><span>Hay {num(summary.Uncounted)} variantes de este alcance sin contar. Si finalizas, su stock permanecerá en cero.</span></div>}{summary.PendingProducts>0&&<p>Los códigos nuevos seguirán pendientes en Productos hasta completar y publicar sus datos.</p>}<div className="cl-button-row"><button className="cl-btn cl-btn-light" disabled={busy} onClick={()=>setConfirmation(null)}>Seguir contando</button><button className="cl-btn cl-btn-dark" disabled={busy} onClick={()=>status('COMPLETED',true)}>{busy?'Guardando…':'Confirmar finalización'}</button></div>{error&&<p className="cl-form-error">{error}</p>}</Modal>}
  {editing&&<Modal title="Datos de la entrada o inventario" onClose={()=>setEditing(false)} busy={busy}><label className="cl-field">Referencia / proveedor<input value={reference} maxLength={190} onChange={e=>setReference(e.target.value)} placeholder="Factura, pedido o proveedor"/></label><label className="cl-field">Notas<textarea value={notes} maxLength={2000} onChange={e=>setNotes(e.target.value)} rows={4}/></label><button className="cl-btn" disabled={busy} onClick={saveMetadata}>Guardar datos</button>{error&&<p className="cl-form-error">{error}</p>}</Modal>}
  {scan&&s&&<InventoryCapture session={s} brands={meta.brands} onClose={()=>setScan(false)} onSaved={async()=>{await refreshDetail();await refreshMeta();}}/>}
 </main></div>;
}
